before:
  hooks:
    - make install

builds:

  - id: darwin
    env:
      - CGO_ENABLED=1
    goos:
      - darwin
    goarch:
      - amd64
    hooks:
      pre:
       - cmd: make version={{.Version}} bundle-darwin
       - cmd: mv bin/darwin/github-notify_{{.Version}}_darwin_x86_64.dmg dist/
    ldflags:
      - -s -w -X main.version={{.Version}}

  - id: linux
    # skip: true
    env:
      - CGO_ENABLED=1
    goos:
      # - linux
      - darwin # fake linux build in macOS in Docker
    goarch:
      - amd64
    ldflags:
      - -s -w -X main.version={{.Version}}
    hooks:
      post:
       - cmd: make version={{.Version}} bundle-linux
       - cmd: rm dist/linux_darwin_amd64/github-notify
       - cmd: mv bin/linux/github-notify dist/linux_darwin_amd64

  - id: windows
    env:
      - CGO_ENABLED=1
    goos:
      - windows
    goarch:
      - amd64
    ldflags:
      - -H=windowsgui
      - -s -w -X main.version={{.Version}}

archives:

  - id: darwin
    builds:
    - darwin
    replacements:
      amd64: x86_64
    files:
      - LICENSE

  - id: linux
    builds:
    - linux
    replacements:
      darwin: linux
      amd64: x86_64
    files:
      - LICENSE

  - id: windows
    builds:
    - windows
    replacements:
      amd64: x86_64
    format: zip
    files:
      - LICENSE

checksum:
  algorithm: sha256

snapshot:
  name_template: 0.0.0-SNAPSHOT-{{.ShortCommit}}

changelog:
  sort: asc
  filters:
    exclude:
      - '^.github:'
      - '^docs:'
      - '^test:'
      - '^assets:'
      - '^docs:'
      - '^readme:'
