name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    name: Release
    runs-on: macos-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.15

    - name: Set up Node.js
      uses: actions/setup-node@v1
      with:
        node-version: ^14.15

    - name: Prerequisites
      run: |
        npm i -g create-dmg
        go get github.com/machinebox/appify
        curl -sfL https://install.goreleaser.com/github.com/goreleaser/goreleaser.sh | sh

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Get dependencies
      run: go get -v -t -d ./...

    - name: Bundle
      run: make release
