name: Release

on:
  push:
    branches: [ master ]

# on:
#   push:
#     tags:
#       - 'v*.*.*'

jobs:

  build-darwin:
    name: Build (macOS)
    runs-on: macos-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.15

    - name: Set up Node.js
      uses: actions/setup-node@v1
      with:
        node-version: ^14.15

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Prerequisites (create-dmg)
      run: npm i -g create-dmg

    - name: Get dependencies
      run: go get -v -t -d ./...

    - name: Bundle
      run: make bundle-darwin
